const APP_VERSION="2.2.0-20260913";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PB_DISTANCES=[30,60,100,120,150,200,300,400,600,800,1000,1500,3000,5000,10000];
let profile={age:18,eventGroup:"sprint",primaryEvent:"100m",pbs:{}},customMenus=[],presets=[],deferredPrompt=null,swReg=null,reloadingForUpdate=false;
document.addEventListener("DOMContentLoaded",init);
async function init(){
 setTimeout(()=>$("#launchScreen")?.classList.add("hide"),650);$("#appVersionLabel").textContent="v"+APP_VERSION;
 $("#trainingDate").value=todayISO();$("#meetDate").value=todayISO();profile=(await getSetting("profile"))||profile;customMenus=(await getSetting("customMenus"))||[];presets=(await getSetting("presets"))||[];
 renderProfile();populateCategories();populatePresetCategory();renderPresetOptions();renderPresetList();renderCustomMenuList();bindUI();renderTimeRows();renderCustomValueRows();await refreshAll();setupPWA();if(location.hash==="#entry")navigate("entryView");else if(location.hash==="#calendar")navigate("calendarView");await checkRemoteVersion(true);
}
function bindUI(){
 $$('[data-nav]').forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.nav)));$("#trainingForm").addEventListener("submit",saveTraining);$("#meetForm").addEventListener("submit",saveMeet);$("#profileForm").addEventListener("submit",saveProfile);$("#presetForm").addEventListener("submit",savePreset);$("#customMenuForm").addEventListener("submit",saveCustomMenu);
 $("#category").addEventListener("change",()=>{toggleEntryType();liveRecalc()});$("#presetSelect").addEventListener("change",applyPreset);$("#distance").addEventListener("input",()=>{renderTimeRows(false);liveRecalc()});$("#reps").addEventListener("input",()=>{renderTimeRows(false);liveRecalc()});$("#sets").addEventListener("input",()=>{renderTimeRows(false);liveRecalc()});$$('input[name="mode"]').forEach(r=>r.addEventListener("change",toggleMode));$("#averageTime").addEventListener("input",liveRecalc);$("#customAttempts").addEventListener("input",()=>{renderCustomValueRows();liveRecalc()});
 $("#detailToggle").addEventListener("click",()=>$("#advancedFields").classList.toggle("hidden"));$("#rpe").addEventListener("input",e=>{$("#rpeValue").textContent=e.target.value+" / 10";liveRecalc()});$("#fatigueBefore").addEventListener("input",e=>{$("#fatigueBeforeValue").textContent=e.target.value+" / 5";liveRecalc()});$("#fatigueAfter").addEventListener("input",e=>{$("#fatigueAfterValue").textContent=e.target.value+" / 5";liveRecalc()});$("#historyCategoryFilter").addEventListener("change",renderHistory);$("#historySearch").addEventListener("input",renderHistory);
 $("#exportBtn").addEventListener("click",exportData);$("#exportBtn2").addEventListener("click",exportData);$("#importInput").addEventListener("change",importData);$("#eventGroup").addEventListener("change",()=>{profile.eventGroup=$("#eventGroup").value;populateCategories();populatePresetCategory()});$("#installBtn").addEventListener("click",triggerInstall);$("#installBtn2").addEventListener("click",triggerInstall);$("#updateBtn").addEventListener("click",forceLatestReload);$("#bookmarkHelpBtn").addEventListener("click",showBookmarkHelp);$("#copyUrlBtn").addEventListener("click",copyCurrentUrl);$("#persistBtn").addEventListener("click",requestPersistentStorage);$("#customMetricType").addEventListener("change",syncCustomDefaults);
}
function navigate(id){$$('.view').forEach(v=>v.classList.toggle("active",v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle("active",b.dataset.nav===id));if(id==="historyView")renderHistory();if(id==="calendarView")renderMeets();if(id==="homeView")renderHome();window.scrollTo({top:0,behavior:"smooth"})}
function todayISO(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function fmtDate(s){return new Intl.DateTimeFormat("ja-JP",{month:"short",day:"numeric",weekday:"short"}).format(new Date(s+"T12:00:00"))}
function secondsFmt(v){if(v==null||!Number.isFinite(v))return"--";if(v>=60){const m=Math.floor(v/60),s=v-m*60;return`${m}:${s.toFixed(2).padStart(5,"0")}`}return v.toFixed(2)+"秒"}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function standardOptions(){return CATEGORY_GROUPS[profile.eventGroup]||CATEGORY_GROUPS.sprint}
function populateCategories(){
 const standard=standardOptions(),favCustom=[...customMenus].sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)||a.name.localeCompare(b.name,"ja"));
 let html=`<optgroup label="標準メニュー">${standard.map(([v,l])=>`<option value="std:${v}">${l}</option>`).join("")}</optgroup>`;
 if(favCustom.length)html+=`<optgroup label="カスタムメニュー（コーチ評価対象外）">${favCustom.map(x=>`<option value="custom:${x.id}">${x.favorite?"★ ":""}${esc(x.name)}</option>`).join("")}</optgroup>`;
 $("#category").innerHTML=html;
 const allStandard=[...new Map(Object.values(CATEGORY_GROUPS).flat().map(x=>[x[0],x])).values()];$("#historyCategoryFilter").innerHTML='<option value="">すべてのメニュー</option><optgroup label="標準">'+allStandard.map(([v,l])=>`<option value="std:${v}">${l}</option>`).join("")+'</optgroup>'+(customMenus.length?'<optgroup label="カスタム">'+customMenus.map(x=>`<option value="custom:${x.id}">${esc(x.name)}</option>`).join("")+'</optgroup>':"");toggleEntryType();
}
function populatePresetCategory(){$("#presetCategory").innerHTML=standardOptions().map(([v,l])=>`<option value="${v}">${l}</option>`).join("")}
function renderProfile(){$("#age").value=profile.age||18;$("#eventGroup").value=profile.eventGroup||"sprint";$("#primaryEvent").value=profile.primaryEvent||"100m";$("#pbEditor").innerHTML=PB_DISTANCES.map(d=>`<label class="pb-entry">${d}m<input data-pb="${d}" type="number" min="0" step="0.01" inputmode="decimal" value="${profile.pbs?.[d]||""}" placeholder="秒"></label>`).join("")}
function parseMenuSelection(){const v=$("#category").value||"";if(v.startsWith("custom:")){const id=v.slice(7);return{isCustom:true,custom:customMenus.find(x=>String(x.id)===id)}}return{isCustom:false,category:v.replace(/^std:/,"")}}
function toggleEntryType(){const sel=parseMenuSelection();$("#standardFields").classList.toggle("hidden",sel.isCustom);$("#customFields").classList.toggle("hidden",!sel.isCustom);if(sel.isCustom&&sel.custom){$("#customMenuTitle").textContent=(sel.custom.favorite?"★ ":"")+sel.custom.name;$("#customBaselineDisplay").value=sel.custom.baseline;$("#customBaselineUnit").textContent=sel.custom.unit;const dir=customDirection(sel.custom);$("#customDirectionHint").textContent=dir==="lower"?"小さいほど高パフォーマンス":"大きいほど高パフォーマンス";renderCustomValueRows()}liveRecalc()}
function renderTimeRows(reset=true){const reps=Math.max(1,Math.min(30,Number($("#reps").value)||1)),sets=Math.max(1,Math.min(10,Number($("#sets").value)||1)),n=Math.min(60,reps*sets),old=$$(".rep-time").map(x=>x.value);$("#timeRows").innerHTML=Array.from({length:n},(_,i)=>`<div class="time-row"><span>${i+1}本目</span><div class="with-unit"><input class="rep-time" type="number" min="0" step="0.01" inputmode="decimal" value="${reset?"":(old[i]||"")}"><span>秒</span></div><span class="ratio-tag" data-ratio-row="${i}">--</span></div>`).join("");$$(".rep-time").forEach(x=>x.addEventListener("input",liveRecalc))}
function renderCustomValueRows(){const sel=parseMenuSelection(),m=sel.custom;if(!m)return;const n=Math.max(1,Math.min(60,Number($("#customAttempts").value)||1)),old=$$(".custom-value").map(x=>x.value);$("#customValueRows").innerHTML=Array.from({length:n},(_,i)=>`<div class="time-row"><span>${i+1}回目</span><div class="with-unit"><input class="custom-value" type="number" min="0" step="0.01" inputmode="decimal" value="${old[i]||""}"><span>${esc(m.unit)}</span></div><span class="ratio-tag"></span></div>`).join("");$$(".custom-value").forEach(x=>x.addEventListener("input",liveRecalc))}
function toggleMode(){const detail=$('input[name="mode"]:checked').value==="detail";$("#detailTimesBlock").classList.toggle("hidden",!detail);$("#simpleTimeBlock").classList.toggle("hidden",detail);liveRecalc()}
function customDirection(m){return m?.evaluationDirection||(m?.metricType==="time"?"lower":"higher")}
function representativeCustom(m,values){if(!values.length)return null;if(m.compareMode==="average")return mean(values);return customDirection(m)==="lower"?Math.min(...values):Math.max(...values)}
function performanceVsBaseline(m,value){if(!m||!value||!m.baseline)return null;return customDirection(m)==="lower"?(m.baseline/value-1)*100:(value/m.baseline-1)*100}
function currentDraft(){const sel=parseMenuSelection();if(sel.isCustom){const m=sel.custom,values=$$(".custom-value").map(x=>Number(x.value)).filter(x=>x>0),rep=representativeCustom(m,values);return{date:$("#trainingDate").value,isCustom:true,customMenuId:m?.id,customMenuName:m?.name,metricType:m?.metricType,unit:m?.unit,baseline:Number(m?.baseline)||null,compareMode:m?.compareMode||"best",evaluationDirection:customDirection(m),values,representativeValue:rep,performancePct:performanceVsBaseline(m,rep),rpe:Number($("#rpe").value),fatigueBefore:Number($("#fatigueBefore").value),fatigueAfter:Number($("#fatigueAfter").value),restMin:Number($("#restMin").value)||null,setRestMin:Number($("#setRestMin").value)||null,notes:$("#notes").value.trim()}}const detail=$('input[name="mode"]:checked').value==="detail",times=detail?$$(".rep-time").map(x=>Number(x.value)).filter(x=>x>0):[],avg=detail?mean(times):Number($("#averageTime").value)||null,dist=Number($("#distance").value)||null,pb=dist?Number(profile.pbs?.[dist])||null:null,ratio=pbRatio(pb,avg);return{date:$("#trainingDate").value,isCustom:false,category:sel.category,distance:dist,reps:Number($("#reps").value)||1,sets:Number($("#sets").value)||1,mode:detail?"detail":"simple",times,averageTime:avg,pb,pbRatio:ratio,dropPct:detail?maxDrop(times):null,rpe:Number($("#rpe").value),fatigueBefore:Number($("#fatigueBefore").value),fatigueAfter:Number($("#fatigueAfter").value),restMin:Number($("#restMin").value)||null,setRestMin:Number($("#setRestMin").value)||null,notes:$("#notes").value.trim()}}
async function liveRecalc(){const d=currentDraft();if(d.isCustom){$("#customRepresentative").textContent=d.representativeValue!=null?`${d.representativeValue.toFixed(2)} ${d.unit}`:"--";$("#customBaselinePreview").textContent=d.baseline?`${Number(d.baseline).toFixed(2)} ${d.unit}`:"--";$("#customPerformancePreview").textContent=d.performancePct!=null?`${d.performancePct>=0?"+":""}${d.performancePct.toFixed(1)}%`:"--";$("#liveCoach").textContent=customCoachNotice();$("#liveCoach").classList.add("custom-note");return}$("#liveCoach").classList.remove("custom-note");$("#pbPreview").textContent=d.pb?secondsFmt(d.pb):"未登録";$("#pbRatioPreview").textContent=d.pbRatio?d.pbRatio.toFixed(1)+"%":"--";$("#dropPreview").textContent=d.dropPct!=null?d.dropPct.toFixed(1)+"%":"--";$$(".rep-time").forEach((el,i)=>{const t=Number(el.value),r=pbRatio(d.pb,t),tag=document.querySelector(`[data-ratio-row="${i}"]`);if(tag)tag.textContent=r?r.toFixed(1)+"%":"--"});const history=await getAll("trainings"),meets=await getAll("meets");$("#liveCoach").textContent=buildCoachComment(d,history,profile,findNextMeet(meets,d.date))}
async function saveTraining(e){e.preventDefault();const d=currentDraft();if(!d.date){toast("日付を入力してください");return}if(d.isCustom){if(!d.customMenuId||!d.representativeValue){toast("カスタムメニューの記録を入力してください");return}}else{if(!d.category||!d.distance){toast("メニューと距離を入力してください");return}if(!d.averageTime&&!["weights","other"].includes(d.category)){toast("タイムを入力してください");return}}const history=await getAll("trainings"),meets=await getAll("meets");d.coach=buildCoachComment(d,history,profile,findNextMeet(meets,d.date));d.createdAt=new Date().toISOString();await addRecord("trainings",d);toast("練習を保存しました");resetTrainingForm();await refreshAll();navigate("homeView")}
function resetTrainingForm(){$("#trainingForm").reset();$("#trainingDate").value=todayISO();$("#reps").value=1;$("#sets").value=1;$("#customAttempts").value=1;$("#rpe").value=5;$("#fatigueBefore").value=2;$("#fatigueAfter").value=3;$("#rpeValue").textContent="5 / 10";$("#fatigueBeforeValue").textContent="2 / 5";$("#fatigueAfterValue").textContent="3 / 5";populateCategories();renderTimeRows();renderCustomValueRows()}
async function saveMeet(e){e.preventDefault();await addRecord("meets",{name:$("#meetName").value.trim(),date:$("#meetDate").value,event:$("#meetEvent").value.trim(),createdAt:new Date().toISOString()});e.target.reset();$("#meetDate").value=todayISO();toast("大会予定を追加しました");await refreshAll()}
async function saveProfile(e){e.preventDefault();const pbs={};$$('[data-pb]').forEach(x=>{const v=Number(x.value);if(v>0)pbs[x.dataset.pb]=v});profile={age:Number($("#age").value)||18,eventGroup:$("#eventGroup").value,primaryEvent:$("#primaryEvent").value,pbs};await setSetting("profile",profile);populateCategories();populatePresetCategory();toast("プロフィールを保存しました");liveRecalc();renderHome()}
async function savePreset(e){e.preventDefault();presets.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:$("#presetName").value.trim(),category:$("#presetCategory").value,distance:Number($("#presetDistance").value),reps:Number($("#presetReps").value)||1,sets:Number($("#presetSets").value)||1,restMin:Number($("#presetRest").value)||null,favorite:$("#presetFavorite").checked});await setSetting("presets",presets);e.target.reset();$("#presetReps").value=3;$("#presetSets").value=1;renderPresetOptions();renderPresetList();toast("入力プリセットを追加しました")}
function renderPresetOptions(){const sorted=[...presets].sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)||a.name.localeCompare(b.name,"ja"));$("#presetSelect").innerHTML='<option value="">プリセットを使わない</option>'+sorted.map(x=>`<option value="${x.id}">${x.favorite?"★ ":""}${esc(x.name)}</option>`).join("")}
function renderPresetList(){if(!presets.length){$("#presetList").innerHTML='<div class="muted">まだプリセットはありません。</div>';return}$("#presetList").innerHTML=[...presets].sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)).map(x=>`<div class="setting-item"><div><strong>${x.favorite?'<span class="star">★</span> ':''}${esc(x.name)}</strong><div class="meta">${esc(CATEGORY_LABELS[x.category]||x.category)} / ${x.distance}m × ${x.reps}${x.sets>1?' × '+x.sets+'set':''}${x.restMin?' / R='+x.restMin+'分':''}</div></div><div class="setting-actions"><button class="star-btn ${x.favorite?'active':''}" onclick="togglePresetFavorite('${x.id}')" type="button">★</button><button class="delete-btn" onclick="removePreset('${x.id}')" type="button">削除</button></div></div>`).join("")}
async function togglePresetFavorite(id){const x=presets.find(p=>String(p.id)===String(id));if(x)x.favorite=!x.favorite;await setSetting("presets",presets);renderPresetOptions();renderPresetList()}
async function removePreset(id){if(!confirm("このプリセットを削除しますか？"))return;presets=presets.filter(x=>String(x.id)!==String(id));await setSetting("presets",presets);renderPresetOptions();renderPresetList()}
function applyPreset(){const p=presets.find(x=>String(x.id)===$("#presetSelect").value);if(!p)return;$("#category").value=`std:${p.category}`;$("#distance").value=p.distance;$("#reps").value=p.reps;$("#sets").value=p.sets;$("#restMin").value=p.restMin||"";toggleEntryType();renderTimeRows();liveRecalc()}
function syncCustomDefaults(){const type=$("#customMetricType").value;$("#customUnit").value=type==="time"?"秒":"m";$("#customEvaluationDirection").value=type==="time"?"lower":"higher"}
async function saveCustomMenu(e){e.preventDefault();const m={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:$("#customMenuName").value.trim(),metricType:$("#customMetricType").value,unit:$("#customUnit").value,baseline:Number($("#customBaseline").value),evaluationDirection:$("#customEvaluationDirection").value,compareMode:$("#customCompareMode").value,favorite:$("#customFavorite").checked};customMenus.push(m);await setSetting("customMenus",customMenus);e.target.reset();syncCustomDefaults();populateCategories();renderCustomMenuList();toast("カスタムメニューを追加しました")}
function renderCustomMenuList(){if(!customMenus.length){$("#customMenuList").innerHTML='<div class="muted">まだカスタムメニューはありません。</div>';return}$("#customMenuList").innerHTML=[...customMenus].sort((a,b)=>(b.favorite?1:0)-(a.favorite?1:0)).map(x=>`<div class="setting-item"><div><strong>${x.favorite?'<span class="star">★</span> ':''}${esc(x.name)}</strong><div class="meta">${x.metricType==='time'?'時間':'距離'} / 基準 ${Number(x.baseline).toFixed(2)}${esc(x.unit)} / ${customDirection(x)==='lower'?'小さいほど高評価':'大きいほど高評価'} / ${x.compareMode==='average'?'平均比較':'ベスト比較'} / コーチ評価対象外</div></div><div class="setting-actions"><button class="star-btn ${x.favorite?'active':''}" onclick="toggleCustomFavorite('${x.id}')" type="button">★</button><button class="delete-btn" onclick="removeCustomMenu('${x.id}')" type="button">削除</button></div></div>`).join("")}
async function toggleCustomFavorite(id){const x=customMenus.find(p=>String(p.id)===String(id));if(x)x.favorite=!x.favorite;await setSetting("customMenus",customMenus);populateCategories();renderCustomMenuList()}
async function removeCustomMenu(id){if(!confirm("このカスタムメニューを削除しますか？過去の記録は残ります。"))return;customMenus=customMenus.filter(x=>String(x.id)!==String(id));await setSetting("customMenus",customMenus);populateCategories();renderCustomMenuList()}
async function refreshAll(){await Promise.all([renderHome(),renderHistory(),renderMeets()]);liveRecalc()}
function startOfWeek(d=new Date()){const x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x}
async function renderHome(){$("#todayLabel").textContent=new Intl.DateTimeFormat("ja-JP",{month:"long",day:"numeric",weekday:"short"}).format(new Date());const all=(await getAll("trainings")).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id),meets=await getAll("meets"),s=startOfWeek(),e=new Date(s);e.setDate(e.getDate()+7);const week=all.filter(x=>{const d=new Date(x.date+"T12:00:00");return d>=s&&d<e}),standard=week.filter(x=>!x.isCustom),highs=standard.filter(x=>["high","very_high"].includes(intensityFromRatio(x.pbRatio))).length;$("#weekSessions").textContent=week.length+" 回";$("#weekHigh").textContent=highs+" 回";const next=findNextMeet(meets);$("#weeklyCoach").textContent=buildWeeklyCoach(week,profile,next);$("#homeSummary").textContent=week.length?`今週 ${week.length}回｜標準 ${standard.length}回｜カスタム ${week.length-standard.length}回｜専門 ${profile.primaryEvent}`:`専門 ${profile.primaryEvent}｜最初の練習を記録しましょう`;$("#nextMeet").innerHTML=next?`<strong>${esc(next.name)}</strong><div class="meta">${fmtDate(next.date)} ${esc(next.event||"")}</div>`:"大会予定はまだありません。";$("#recentList").classList.toggle("empty",!all.length);$("#recentList").innerHTML=all.length?all.slice(0,4).map(trainingRow).join(""):"まだ練習記録がありません。"}
function fatigueText(x){const b=Number(x.fatigueBefore||x.fatigue||0),a=Number(x.fatigueAfter||x.fatigue||0);return b&&a?`${b}→${a}/5`:b?`${b}/5`:"--"}
function trainingRow(x){if(x.isCustom)return`<div class="list-item"><div class="item-top"><span class="item-title"><span class="pill accent">カスタム</span> ${esc(x.customMenuName||"カスタムメニュー")}</span><span>${x.performancePct!=null?(x.performancePct>=0?"+":"")+x.performancePct.toFixed(1)+"%":""}</span></div><div class="meta">${fmtDate(x.date)}｜${x.representativeValue!=null?Number(x.representativeValue).toFixed(2)+esc(x.unit||""):"--"}｜疲労 ${fatigueText(x)}｜メニュー評価対象外</div></div>`;return`<div class="list-item"><div class="item-top"><span class="item-title">${esc(CATEGORY_LABELS[x.category]||x.category)} ${x.distance||""}m × ${x.reps||1}${x.sets>1?` × ${x.sets}set`:""}</span><span>${x.pbRatio?x.pbRatio.toFixed(1)+"%":""}</span></div><div class="meta">${fmtDate(x.date)}｜平均 ${secondsFmt(x.averageTime)}｜疲労 ${fatigueText(x)}</div></div>`}
async function renderHistory(){const filter=$("#historyCategoryFilter")?.value||"",q=($("#historySearch")?.value||"").toLowerCase();let all=(await getAll("trainings")).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);all=all.filter(x=>{const key=x.isCustom?`custom:${x.customMenuId}`:`std:${x.category}`,text=`${x.distance||""} ${x.notes||""} ${x.customMenuName||""} ${CATEGORY_LABELS[x.category]||""}`.toLowerCase();return(!filter||key===filter)&&(!q||text.includes(q))});$("#historyList").classList.toggle("empty",!all.length);$("#historyList").innerHTML=all.length?all.map(x=>x.isCustom?`<article class="history-card"><div class="item-top"><div><strong>${fmtDate(x.date)}｜<span class="pill accent">カスタム</span> ${esc(x.customMenuName||"カスタムメニュー")}</strong><div class="meta">代表値 ${Number(x.representativeValue||0).toFixed(2)}${esc(x.unit||"")}｜基準 ${Number(x.baseline||0).toFixed(2)}${esc(x.unit||"")}｜パフォーマンス ${x.performancePct!=null?(x.performancePct>=0?"+":"")+x.performancePct.toFixed(1)+"%":"--"}｜疲労 ${fatigueText(x)}</div></div><button class="delete-btn" onclick="removeTraining(${x.id})">削除</button></div>${x.notes?`<div class="meta">メモ：${esc(x.notes)}</div>`:""}<div class="coach-message custom-note">${esc(x.coach||customCoachNotice())}</div></article>`:`<article class="history-card"><div class="item-top"><div><strong>${fmtDate(x.date)}｜${esc(CATEGORY_LABELS[x.category]||x.category)}</strong><div class="meta">${x.distance||"-"}m × ${x.reps||1}${x.sets>1?` × ${x.sets}set`:""}｜平均 ${secondsFmt(x.averageTime)} ${x.pbRatio?`｜PB比 ${x.pbRatio.toFixed(1)}%`:""}｜疲労 ${fatigueText(x)}</div></div><button class="delete-btn" onclick="removeTraining(${x.id})">削除</button></div>${x.notes?`<div class="meta">メモ：${esc(x.notes)}</div>`:""}<div class="coach-message">${esc(x.coach||"")}</div></article>`).join(""):"条件に合う記録がありません。"}
async function removeTraining(id){if(!confirm("この練習記録を削除しますか？"))return;await deleteRecord("trainings",id);toast("削除しました");await refreshAll()}
async function renderMeets(){const all=(await getAll("meets")).sort((a,b)=>a.date.localeCompare(b.date));$("#meetList").innerHTML=all.length?all.map(x=>`<article class="meet-card"><div class="item-top"><div><strong>${esc(x.name)}</strong><div class="meta">${fmtDate(x.date)}｜${esc(x.event||"種目未入力")}</div></div><button class="delete-btn" onclick="removeMeet(${x.id})">削除</button></div></article>`).join(""):'<div class="card empty">大会予定はまだありません。</div>'}
async function removeMeet(id){if(!confirm("この大会予定を削除しますか？"))return;await deleteRecord("meets",id);await refreshAll()}
function findNextMeet(meets,base=todayISO()){return[...meets].filter(x=>x.date>=base).sort((a,b)=>a.date.localeCompare(b.date))[0]||null}
async function exportData(){const data={version:3,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),profile,customMenus,presets,trainings:await getAll("trainings"),meets:await getAll("meets")},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`track-log-backup-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(e){const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!Array.isArray(data.trainings)||!Array.isArray(data.meets))throw new Error("形式不正");if(!confirm("現在のデータにバックアップ内容を追加します。よろしいですか？"))return;if(data.profile){profile=data.profile;await setSetting("profile",profile);renderProfile()}if(Array.isArray(data.customMenus)){customMenus=data.customMenus;await setSetting("customMenus",customMenus)}if(Array.isArray(data.presets)){presets=data.presets;await setSetting("presets",presets)}for(const x of data.trainings){const y={...x};delete y.id;await addRecord("trainings",y)}for(const x of data.meets){const y={...x};delete y.id;await addRecord("meets",y)}populateCategories();populatePresetCategory();renderPresetOptions();renderPresetList();renderCustomMenuList();toast("バックアップを復元しました");await refreshAll()}catch(err){toast("復元に失敗しました："+err.message)}e.target.value=""}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2800)}
function setupPWA(){const ua=navigator.userAgent,isIOS=/iphone|ipad|ipod/i.test(ua),standalone=window.matchMedia("(display-mode: standalone)").matches||navigator.standalone;if(standalone){$("#installHelp").textContent="この端末ではホーム画面アプリとして起動しています。起動時・オンライン復帰時・画面復帰時に最新版確認を行います。";$("#installBtn2").classList.add("hidden")}else if(isIOS){$("#installHelp").textContent="iPhone/iPad：Safariで開き、共有ボタン →「ホーム画面に追加」を選んでください。通常のブックマークは共有ボタン →「ブックマークを追加」です。"}else{$("#installHelp").textContent="対応ブラウザでは「ホーム画面に追加」からPWAとして登録できます。表示されない場合はブラウザメニューの「アプリをインストール／ホーム画面に追加」を確認してください。"}window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden");$("#installBtn2").classList.remove("hidden")});window.addEventListener("appinstalled",()=>{deferredPrompt=null;$("#installBtn").classList.add("hidden");toast("ホーム画面に追加されました")});if("serviceWorker"in navigator){navigator.serviceWorker.register("./service-worker.js?v=20260913r3",{updateViaCache:"none"}).then(reg=>{swReg=reg;reg.update();reg.addEventListener("updatefound",()=>{$("#updateBanner").classList.remove("hidden")})}).catch(err=>console.error("SW registration failed",err));navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!reloadingForUpdate){reloadingForUpdate=true;location.reload()}})}document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")checkRemoteVersion(true)});window.addEventListener("online",()=>checkRemoteVersion(true));setInterval(()=>checkRemoteVersion(true),30*60*1000)}
async function triggerInstall(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").classList.add("hidden");return}showBookmarkHelp(true)}
function showBookmarkHelp(homeOnly=false){const ua=navigator.userAgent;if(/iphone|ipad|ipod/i.test(ua))alert(homeOnly?"Safariの共有ボタン →『ホーム画面に追加』を選択してください。":"Safariの共有ボタンから『ホーム画面に追加』または『ブックマークを追加』を選択してください。");else if(/android/i.test(ua))alert(homeOnly?"ブラウザ右上のメニューから『アプリをインストール』または『ホーム画面に追加』を選択してください。":"ブラウザ右上のメニューから『ブックマーク（★）』または『ホーム画面に追加／アプリをインストール』を選択してください。");else alert("ブラウザのブックマーク機能をご利用ください。Windows/Linuxでは多くのブラウザで Ctrl+D、Macでは Command+D です。PWA対応ブラウザではアドレスバー付近のインストールアイコンも利用できます。")}
async function copyCurrentUrl(){try{await navigator.clipboard.writeText(location.href.split("?")[0]);toast("URLをコピーしました")}catch{toast("URLをコピーできませんでした")}}
async function requestPersistentStorage(){if(!navigator.storage?.persist){toast("このブラウザは保存保護APIに対応していません");return}const ok=await navigator.storage.persist();toast(ok?"端末保存の保護が有効になりました":"ブラウザ側で保存保護が許可されませんでした")}
async function checkRemoteVersion(auto=false){if(!navigator.onLine)return;try{const res=await fetch(`./version.json?ts=${Date.now()}`,{cache:"no-store",headers:{"Cache-Control":"no-cache, no-store, max-age=0"}});if(!res.ok)return;const remote=await res.json();if(remote.version&&remote.version!==APP_VERSION){$("#updateBanner").classList.remove("hidden");if(swReg)await swReg.update();if(auto)setTimeout(forceLatestReload,250)}}catch(e){console.debug("version check skipped",e)}}
async function forceLatestReload(){if(reloadingForUpdate)return;reloadingForUpdate=true;try{if(swReg)await swReg.update();const regs=await navigator.serviceWorker?.getRegistrations?.();if(regs)for(const r of regs)r.update?.()}catch{}const base=location.href.split("?")[0].split("#")[0];location.replace(`${base}?fresh=${Date.now()}`)}
